backbone: vit-s-16
base_teacher_momentum: 0.996
base_weight_decay: 0.04
batch_size: 1024
bottleneck_dim: 256
center_momentum: 0.9
epochs: 100
experiment_num: 1
final_lr: 1.0e-06
final_teacher_momentum: 1.0
final_teacher_temp: 0.04
final_weight_decay: 0.4
global_scale_max: 1.0
global_scale_min: 0.4
hidden_dim: 2048
k_dim: 65536
local_scale_max: 0.4
local_scale_min: 0.05
mlp_layers: 3
num_local_crops: 10
seed: 42
student_temp: 0.1
warmup_epochs_lr: 10
warmup_start_lr: 0.0
warmup_teacher_epochs: 0
warmup_teacher_temp: 0.04
